# Generated by Django 2.2.12 on 2022-11-19 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221115_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now)),
                ('uaraian', models.CharField(max_length=100)),
                ('debit', models.IntegerField(default=0)),
                ('kredit', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
    ]
