# Generated by Django 2.2.12 on 2022-11-19 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221119_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='alamat',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costumer',
            name='harga',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='jumlahbrg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='nama',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='namabrg',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='totalbyr',
            field=models.BigIntegerField(),
        ),
    ]
